"use client";

import React from 'react';
import { AdiabaticCoolingTemplateProps } from './types';
import { calculateMetrics, formatters } from './utils/calculations';
import './styles/report-template.css';
import CoverPage from './components/CoverPage';

/**
 * 📋 Professional Report Template for Adiabatic Cooling Proposals
 * Designed for PDF generation and professional printing
 * Clean, document-style layout without web UI elements
 */
export default function ReportTemplate({ data }: AdiabaticCoolingTemplateProps) {
  const metrics = calculateMetrics(data);

  // Helper function to safely convert string to number for currency formatting
  const safeCurrency = (value: string | number): string => {
    const numValue = typeof value === 'string' ? parseFloat(value) : value;
    return formatters.currency(numValue);
  };

  // Default technology highlights for the cover page
  const techHighlights = [
    {
      icon: (
        <svg width="32" height="32" fill="none" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#E0F2FE"/><path d="M10 22V10h12v12H10zm2-2h8V12h-8v8z" fill="#0369A1"/></svg>
      ),
      title: 'Digital Twin Technology',
      description: 'Our solution leverages digital twin technology to simulate and optimize system performance before implementation, ensuring maximum efficiency.',
      tags: ['Real-time', 'Predictive'],
    },
    {
      icon: (
        <svg width="32" height="32" fill="none" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#D1FAE5"/><path d="M16 10a6 6 0 016 6c0 3.314-6 10-6 10s-6-6.686-6-10a6 6 0 016-6zm0 8a2 2 0 100-4 2 2 0 000 4z" fill="#059669"/></svg>
      ),
      title: 'IoT-Enabled Monitoring',
      description: 'Real-time data collection and analysis through IoT sensors for performance optimization and predictive maintenance.',
      tags: ['Smart Control', 'Cloud Connected'],
    },
  ];

  return (
    <div className="report-template">
      {/* Cover Page */}
      <CoverPage
        companyName="SeeTech"
        tagline="Delivering Profits & Sustainability Together"
        title="Adiabatic Cooling System"
        capacity={`for ${data.systemCapacity} TR`}
        clientName={data.clientName}
        clientLocation={data.location}
        badgeText="INTELLIGENT SOLUTION"
        projectName={data.projectName}
        date={new Date(data.date).toLocaleDateString()}
        techHighlights={techHighlights}
        footerNote={
          'Note: This proposal is generated by the system with detailed energy calculations and technical analysis.'
        }
      />
      <div className="page-break"></div>

      {/* Report Header */}
      <header className="report-header">
        <div className="company-logo">
          <h1>SeeTech Engineering Solutions</h1>
          <p>Advanced HVAC & Energy Solutions</p>
        </div>
        <div className="proposal-meta">
          <h2>TECHNICAL PROPOSAL</h2>
          <p>Proposal No: {data.proposalNumber}</p>
          <p>Date: {new Date(data.date).toLocaleDateString()}</p>
        </div>
      </header>

      {/* Title Page */}
      <section className="title-section">
        <h1 className="proposal-title">{data.projectName}</h1>
        <h2 className="subtitle">Adiabatic Cooling System Implementation</h2>
        
        <div className="client-info">
          <h3>Prepared For:</h3>
          <p className="client-name">{data.clientName}</p>
          <p className="client-location">{data.location}</p>
          <p className="contact">Contact: {data.contactPerson}</p>
          <p className="contact">Email: {data.contactEmail}</p>
          <p className="contact">Phone: {data.contactPhone}</p>
        </div>

        <div className="engineer-info">
          <h3>Prepared By:</h3>
          <p>{data.engineerName}</p>
          <p>SeeTech Engineering Solutions</p>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Executive Summary */}
      <section className="executive-summary">
        <h2 className="section-title">EXECUTIVE SUMMARY</h2>
        
        <p className="summary-text">
          This proposal presents a comprehensive analysis for implementing an adiabatic cooling 
          system to improve the energy efficiency of your existing {data.chillerType} installation. 
          Our analysis indicates potential energy savings of {data.expectedSaving}% with a 
          payback period of {data.paybackPeriod} years.
        </p>

        <div className="key-highlights">
          <h3>Key Benefits</h3>
          <ul className="benefits-list">
            <li>Energy Cost Savings: ₹{formatters.currency(metrics.annualMonetarySaving)} per year</li>
            <li>CO₂ Reduction: {data.co2Reduction} kg annually</li>
            <li>Water Conservation: {data.waterSaving} liters annually</li>
            <li>ROI: {data.roi}%</li>
          </ul>
        </div>
      </section>

      {/* Technical Analysis */}
      <section className="technical-analysis">
        <h2 className="section-title">TECHNICAL ANALYSIS</h2>

        <div className="system-comparison">
          <h3>Current vs. Proposed System Performance</h3>
          
          <table className="comparison-table">
            <thead>
              <tr>
                <th>Parameter</th>
                <th>Current System</th>
                <th>Proposed System</th>
                <th>Improvement</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>System Capacity</td>
                <td>{data.systemCapacity} TR</td>
                <td>{data.systemCapacity} TR</td>
                <td>-</td>
              </tr>
              <tr>
                <td>Power Consumption</td>
                <td>{data.currentPower} kW</td>
                <td>{metrics.afterPowerKW.toFixed(1)} kW</td>
                <td>{metrics.savingKW.toFixed(1)} kW</td>
              </tr>
              <tr>
                <td>Efficiency</td>
                <td>{data.currentEfficiency}%</td>
                <td>{data.proposedEfficiency}%</td>
                <td>+{data.expectedSaving}%</td>
              </tr>
              <tr>
                <td>Annual Energy Cost</td>
                <td>₹{safeCurrency(data.currentOperatingCost)}</td>
                <td>₹{formatters.currency(parseFloat(data.currentOperatingCost) - metrics.annualMonetarySaving)}</td>
                <td>₹{formatters.currency(metrics.annualMonetarySaving)}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="operating-conditions">
          <h3>Design Operating Conditions</h3>
          <div className="conditions-grid">
            <div className="condition-item">
              <span className="label">Ambient Temperature:</span>
              <span className="value">{data.ambientTemperature}°C</span>
            </div>
            <div className="condition-item">
              <span className="label">Chilled Water Temperature:</span>
              <span className="value">{data.chillWaterTemperature}°C</span>
            </div>
            <div className="condition-item">
              <span className="label">Wet Bulb Temperature:</span>
              <span className="value">{data.wetBulbTemperature}°C</span>
            </div>
            <div className="condition-item">
              <span className="label">Relative Humidity:</span>
              <span className="value">{data.humidity}%</span>
            </div>
            <div className="condition-item">
              <span className="label">Operating Hours:</span>
              <span className="value">{data.operatingHours} hrs/day</span>
            </div>
            <div className="condition-item">
              <span className="label">Operating Days:</span>
              <span className="value">{data.operatingDays} days/year</span>
            </div>
          </div>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Financial Analysis */}
      <section className="financial-analysis">
        <h2 className="section-title">FINANCIAL ANALYSIS</h2>

        <div className="investment-summary">
          <h3>Investment Summary</h3>
          <table className="financial-table">
            <tbody>
              <tr>
                <td>Total Investment Cost</td>
                <td className="amount">₹{safeCurrency(data.investmentCost)}</td>
              </tr>
              <tr>
                <td>Annual Energy Savings</td>
                <td className="amount">₹{formatters.currency(metrics.annualMonetarySaving)}</td>
              </tr>
              <tr>
                <td>Simple Payback Period</td>
                <td className="amount">{data.paybackPeriod} years</td>
              </tr>
              <tr>
                <td>Return on Investment (ROI)</td>
                <td className="amount">{data.roi}%</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="savings-projection">
          <h3>10-Year Savings Projection</h3>
          <table className="projection-table">
            <thead>
              <tr>
                <th>Year</th>
                <th>Annual Savings</th>
                <th>Cumulative Savings</th>
                <th>Net Benefit</th>
              </tr>
            </thead>
            <tbody>
              {Array.from({ length: 10 }, (_, i) => {
                const year = i + 1;
                const annualSavings = metrics.annualMonetarySaving;
                const cumulativeSavings = annualSavings * year;
                const netBenefit = cumulativeSavings - parseFloat(data.investmentCost);
                
                return (
                  <tr key={year}>
                    <td>{year}</td>
                    <td>₹{formatters.currency(annualSavings)}</td>
                    <td>₹{formatters.currency(cumulativeSavings)}</td>
                    <td className={netBenefit > 0 ? 'positive' : 'negative'}>
                      ₹{formatters.currency(Math.abs(netBenefit))}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      {/* Environmental Impact */}
      <section className="environmental-impact">
        <h2 className="section-title">ENVIRONMENTAL IMPACT</h2>
        
        <div className="environmental-benefits">
          <div className="benefit-item">
            <h4>Carbon Footprint Reduction</h4>
            <p className="benefit-value">{data.co2Reduction} kg CO₂/year</p>
            <p className="benefit-desc">Equivalent to planting {Math.round(parseFloat(data.co2Reduction) / 22)} trees annually</p>
          </div>
          
          <div className="benefit-item">
            <h4>Water Conservation</h4>
            <p className="benefit-value">{data.waterSaving} liters/year</p>
            <p className="benefit-desc">Through improved efficiency and reduced cooling water requirements</p>
          </div>
        </div>
      </section>

      <div className="page-break"></div>

      {/* Implementation Plan */}
      <section className="implementation-plan">
        <h2 className="section-title">IMPLEMENTATION PLAN</h2>
        
        <div className="project-phases">
          <div className="phase">
            <h4>Phase 1: Site Assessment & Design (Week 1-2)</h4>
            <ul>
              <li>Detailed site survey and measurements</li>
              <li>Final system design and engineering drawings</li>
              <li>Equipment procurement and delivery scheduling</li>
            </ul>
          </div>
          
          <div className="phase">
            <h4>Phase 2: Installation (Week 3-4)</h4>
            <ul>
              <li>Pre-cooling system installation</li>
              <li>Piping and electrical connections</li>
              <li>Control system integration</li>
            </ul>
          </div>
          
          <div className="phase">
            <h4>Phase 3: Commissioning & Testing (Week 5)</h4>
            <ul>
              <li>System startup and performance testing</li>
              <li>Staff training and documentation handover</li>
              <li>Performance verification and warranty activation</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Conclusion */}
      <section className="conclusion">
        <h2 className="section-title">CONCLUSION</h2>
        
        <p>
          The proposed adiabatic cooling system offers a compelling business case with significant 
          energy savings, environmental benefits, and a strong return on investment. The {data.paybackPeriod}-year 
          payback period and {data.roi}% ROI make this project financially attractive while supporting 
          your sustainability goals.
        </p>
        
        <p>
          We recommend proceeding with this implementation to achieve immediate operational cost 
          reductions and long-term energy efficiency improvements.
        </p>
      </section>

      {/* Report Footer */}
      <footer className="report-footer">
        <div className="footer-line"></div>
        <p>SeeTech Engineering Solutions | {data.proposalNumber} | Page {'{page}'}</p>
      </footer>
    </div>
  );
}
